.Dd $Mdocdate$
.Dt ABSTAIN 1
.Os
.Sh NAME
.Nm abstain
.Nd execute programs with reduced
.Xr pledge 2
promises
.Sh SYNOPSIS
.Nm abstain
.Bk -words
.Op Fl v Ar vice[,vice,...]
.Op Fl - Ar command Ar commandflags
.Sh DESCRIPTION
The
.Nm
utility ...
.Sh EXAMPLES
.Sh EXIT STATUS
.Sh SEE ALSO
.Xr pledge 2
.Xr unveilro 1
.Sh CAVEATS
\&...
.Sh AUTHORS
.An -nosplit
.An Thomas Frohwein Aq Mt thfr@openbsd.org
