.Dd $Mdocdate$
.Dt ABSTAIN 1
.Os
.Sh NAME
.Nm abstain
.Nd selectively disallow
.Xr pledge 2
promises for program execution
.Sh SYNOPSIS
.Nm abstain
.Op Fl le
.Op Fl v Ar \&vice[,vice,...]
.Ar binary Op Ar arguments Ar ...
.Sh DESCRIPTION
The
.Nm
utility executes
.Ar binary
with
.Ar arguments
using
.Xr pledge 2
.Em execpromises .
By default, it will do so with all
.Em execpromises
allowed.
.Pp
Specify
.Ar vices
with
.Fl v
in a comma-separated list.
They represent the exact same concept as
.Em promises
in
.Xr pledge 2 ,
except that their effect is the reverse - they
prohibit
access to syscalls by removing the corresponding
.Xr pledge 2
.Em promise
from the
.Em execpromises .
.Pp
The
.Fl e
flag adds the
.Sq error
.Em promise
.Pq which is not included by default
so that a violation will lead to
.Dv ENOSYS
instead of
.Dv SIGABRT .
.Pp
The
.Fl l
flag prints all possible
.Ar vices
to the standard output.
.Pp
The main use case that
.Nm
is designed for is to gather empirical behavioral data on software for specific types of syscalls, building on
.Xr pledge 2
.Em promise
sets. Ideally, this is part of a comprehensive investigation that includes source code review and a study of kernel trace logs
.Po
see
.Xr ktrace 1
.Pc .
.Sh EXAMPLES
Execute
.Pa binary
with
.Ar arguments ,
prohibiting access to the syscalls of the
.Sq wpath
and
.Sq cpath
groups
.Po see
.Xr pledge 2
for details
.Pc :
.Bd -literal -offset indent
$ abstain -v wpath,cpath binary arguments
.Sh EXIT STATUS
As
.Nm
calls
.Xr execvp 3 ,
it has no process to return to. If any error occurs prior to or when calling
.Xr execvp 3 ,
.Nm
will return -1.
.Sh SEE ALSO
.Xr pledge 2
.Xr execvp 3
.Xr unveilro 1
.Sh AUTHORS
.An -nosplit
.An Thomas Frohwein Aq Mt thfr@openbsd.org
.Sh CAVEATS
Avoid relying on
.Nm
to restrain your programs. The use of
.Xr pledge 2
modification inside the program source is a superior option wherever feasible. The intended use cases are investigation of external program behavior as part of a development process to add more robust restriction with
.Xr pledge 2 ,
or educational to understand the breadth of syscall use.
.Pp
Some system calls when allowed still have restrictions applied to them. Refer to
.Xr pledge 2
for details.
.Pp
Programs violating their
.Xr pledge 2
restrictions by invoking syscalls from one of the
.Ar vices
are killed with uncatchable
.Dv SIGABRT .
.Pp
When running with
.Fl e ,
the
.Sq error
.Em promise
comes with risk that the program can enter inconsistent state, especially
.Xr setuid 2
or
.Xr setgid 2
programs.
